### PR TITLE
Explanation vedio

### PR DESCRIPTION
**Pull request by lassmara**
issue :Create a locally Setup video #44, kindly review it

### CODE REVIEW

**Review by heysagnik — CHANGES_REQUESTED** [review]
The video you made is good, but here the issue asks to create a local setup of the project. As because this is a flutter-based project, you should add few more steps such as how to install flutter sdk (if he is a beginner) and after installation how to setup, like running `flutter pub get` and finally how to build/ run the app for testing purpose such as `flutter run android` etc. etc. This video will guide the newbie to get into this project in a much better way

**Comment by Naveenchand06** [comment]
@lassmara  @heysagnik I noticed that you deleted the project setup video because it didn't cover the prerequisites and tools installation. While I understand the concern, I believe that the video still holds value for those who already have a basic understanding of Flutter.

Instead of removing the video entirely, we could keep it available for now. This way, those with some prior knowledge can benefit from it. Once the new video covering the tools installation is ready, we can replace the current one.

**Comment by heysagnik** [comment]
> @lassmara @heysagnik I noticed that you deleted the project setup video because it didn't cover the prerequisites and tools installation. While I understand the concern, I believe that the video still holds value for those who already have a basic understanding of Flutter.
> 
> Instead of removing the video entirely, we could keep it available for now. This way, those with some prior knowledge can benefit from it. Once the new video covering the tools installation is ready, we can replace the current one.

This is not deleted , check the other PR

**Comment by lassmara** [comment]
hi  @heysagnik , i renamed it and made a PR and also increased the quality of vedio pls check. Meanwhile i will work on adding Firebase setup for this project

**Comment by heysagnik** [comment]
Yeah I saw it , told the project admin to merge , rest you can continue 👍
@lassmara

**Pull request closed without merging**
